# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: ERC721indexer
description: ERC-721 indexer
contracts:
  - name: Analizer
    abi_file_path: ./abis/Analizer.json
    handler: ./src/EventHandlers.ts
    events:
      - event: "Analized(uint256 indexed callId, address targetContract, string functionName, string description, uint256 value, uint8 complexity, uint8 riskLevel)"
networks:
  # - id: 17000 # Holesky Testnet
  #   start_block: 2281499
  #   contracts:
  #     - name: BaseNft
  #       address: "0x3784213D4D5057AF218dA4ee8149B5d35fca8e06"
  - id: 696969 # Galadriel Devnet
    start_block: 35292729
    contracts:
      - name: Analizer
        address: "0x8E25DDF6744f46e6BD2C021499E5a1A48312329D"
rollback_on_reorg: false
